### ISSUE TITLE
soil types db

### ISSUE THREAD

**Issue by gerardhros** [springgbv/Open-Bodem-Index-Calculator#7]
hi,

Today I prepared a grid for whole of the Netherlands with the following soil types:
"dalgrond","dekzand","duinzand","loess","maasklei","rivierklei" ,"veen","venigeklei","zavel", en "zeeklei". Please, adjust the included soils.obic database so that the agronomic functions can make use of these new soil types for subsetting.

For sulpher we also need the agricultural economic zoning within the Netherlands. That is a shapefile with 14 areas. Need to be added to the input as variable B_LG_CBS. Shape available via pdok (and available in raster stack as lbgebied).

Regards  Gerard

**Comment by SvenVw** [comment]
Zavel is a texture type and not used in Handboek Bodem en Bemesting. I think it is better to classify the "zavel" soil into the already existing soil types.

Ok, we include `B_LG_CBS` to the input data in the next release
